### ISSUE TITLE
Doppler smearing support and scalloping loss question

### ISSUE THREAD

**Issue by telegraphic** [bbrzycki/setigen#16]
Hey @bbrzycki, I'm working on some dedoppler efficiency tests, which brought up some setigen questions!

Firstly, how does setigen deal with signals with a drift rate larger than `freq_resolution / time_resolution`? (At first glance it didn't look like this was supported). The power for these will be spread over multiple channels causing 'smearing' and associated loss in S/N.

Secondly, I am realising that the FFT (or PFB) will affect how drifting signals manifest. A signal that starts in the middle of channel `F0` will drift into channel `F1`, but there will be a period of time in which it is halfway between the two -- at which point it will actually appear in both channels, but at a lower S/N. There is also some 'scalloping loss' which occurs as the signal leaks across the full spectrum. Here's a simulation I did with a chirped waveform into an FFT filterbank:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/713251/106224802-141bf800-6238-11eb-80c1-3e3869bdd422.png">

(you can do better with an oversampled PFB).

To accurately evaluate dedoppler efficiency we would need to take both into account. I think doppler smearing would be straightforward to implement, but scalloping loss would be a bit of a nightmare -- and would depend on what kind of filterbank you had.

**Comment by telegraphic** [comment]
On second thought, I think scalloping loss should be ignored -- it is ok for `setigen` to treat the filterbank as if it has perfect channel response. Scalloping loss can be computed separately. 

Smearing across multiple frequency channels at high drift rates is important though to be able to simulate

**Comment by bbrzycki** [comment]
I looked into this more closely, wrote a notebook with some options for this: https://github.com/bbrzycki/setigen/blob/doppler_smearing/jupyter-notebooks/spectrogram/doppler_smearing.ipynb. Added a "doppler_smearing" feature to the `add_signal` and `add_constant_signal` methods of `Frame` to do a numerical approximation for general signals, but it really depends how accurate / computationally expensive things should be.
