### ISSUE TITLE
Frame.save_h5|fil|hdf5 method, defaults defined kwargs, e.g. like tstart, in _update_waterfall method

### ISSUE THREAD

**Issue by marcowenwolf** [bbrzycki/setigen#33]
As demonstrated in the cadences.ippynb in jupyter-notebooks/spectrogram, 6 frames are generated using the SETI ON/OFF cadence. I have saved these frames into 6 frame_0[0-5].h5 files and try to run it against turboSETI/plotSETI. The latter can not find hits using the plotSETI -f3 argument. This is caused by the fact the t_start of the frames are defaulted in the setigen Frame class by the "_update_waterfall" method. Though the t_start is provided as part of the Frame(... **kwargs), its value is defaulted in the mentioned method. This results into a wrong filterbank/h5 headers in the saved files. which do have all the same t_start times, hence plotSETI can not find hits. 

Below the tstart times of the first 2 frames out of 6:
```
(hyperseti) marc@gamma2:~/tmp/test> watutil frame_00.h5 |grep tstart
   tstart (ISOT) :          2018-12-13T17:12:37.000
    tstart (MJD) :               58465.717094907406
(hyperseti) marc@gamma2:~/tmp/test> watutil frame_01.h5 |grep tstart
   tstart (ISOT) :          2018-12-13T17:12:37.000
    tstart (MJD) :               58465.717094907406
```

Sample code based on the jupyter notebook:

```
def create_time_array(cadence_number=6, mjd_start=60000, obs_length=300, slew_time=0):
    '''
    '''
    t_start_arr = [Time(mjd_start, format='mjd').unix]
    for i in range(1, cadence_number):
        t_start_arr.append(t_start_arr[i - 1] + obs_length + slew_time)   
    return t_start_arr

def create_frame(source_name, t_start, df, dt, obs_length):
    '''
    '''
    frame = stg.Frame(fchans=512,
                      tchans=int(obs_length/dt),
                      df=df,
                      dt=18.253611008,
                      fch1=1330*u.MHz,
                      ascending=False,
                      t_start=t_start,
                      source_name=source_name)        
    print(frame.t_start)
    return frame   
```
**Plot of generated frames**
![setigen](https://github.com/bbrzycki/setigen/assets/5303021/c1dab669-eef8-41dd-8f65-7804293bc43b)

**TurboSETI cli log**
For each HDF5 header, tstart is the same **'tstart': 58465.717094907406,**
[turbo_seti_cli.log](https://github.com/bbrzycki/setigen/files/12448864/turbo_seti_cli.log)

**CAMRAS gitlab repo with used code**
https://gitlab.camras.nl/seti/seti_dt_obs/-/blob/main/setigen/camras_gen.py

**Comment by bbrzycki** [comment]
Hi, thanks for raising the issue and including very helpful details! This bug should be fixed with PR #35, and in the new release v2.5.0. Verified that the start times are now updated when writing to file. 
/
